# Generated by Django 4.1.7 on 2023-04-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=50, verbose_name='Логин')),
                ('Password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('Email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('SerName', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('Name', models.CharField(max_length=50, verbose_name='Имя')),
                ('Patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('UserType', models.CharField(max_length=50, verbose_name='Тип пользователя')),
                ('Photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('Time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Пользователи сайта',
                'verbose_name_plural': 'Пользователи сайта',
                'ordering': ['Login'],
            },
        ),
    ]
