# Generated by Django 4.1.7 on 2023-04-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('SerName', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Patronymic', models.CharField(max_length=50)),
                ('UserType', models.CharField(max_length=50)),
                ('Photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('Time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
