# Generated by Django 4.1.7 on 2023-04-11 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang_categori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(max_length=50, verbose_name='Язык программирования')),
            ],
            options={
                'verbose_name': 'Языки программирования',
                'verbose_name_plural': 'Языки программирования',
                'ordering': ['Tittle'],
            },
        ),
        migrations.CreateModel(
            name='Soft_categori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(max_length=50, verbose_name='Категории софта')),
            ],
            options={
                'verbose_name': 'Категории софта',
                'verbose_name_plural': 'Категории софта',
                'ordering': ['Tittle'],
            },
        ),
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(max_length=50, verbose_name='Название анкеты')),
                ('Text', models.CharField(max_length=50, verbose_name='Текст анкеты')),
                ('Status', models.CharField(max_length=50, verbose_name='Статус')),
                ('Photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.users', verbose_name='Автор анкеты')),
                ('Lang_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.lang_categori', verbose_name='Язык программирования')),
                ('Soft_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.soft_categori', verbose_name='Категория софта')),
            ],
            options={
                'verbose_name': 'Анкеты пользователей',
                'verbose_name_plural': 'Анкеты пользователей',
                'ordering': ['Tittle'],
            },
        ),
    ]
