# Generated by Django 4.1.7 on 2023-04-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lang_categori_soft_categori_anketa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Patronymic',
        ),
        migrations.AddField(
            model_name='users',
            name='Birth_date',
            field=models.DateTimeField(default="2004-08-28", verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
