# Generated by Django 4.1.7 on 2023-04-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_users_patronymic_users_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='Text',
            field=models.TextField(max_length=500, verbose_name='Текст анкеты'),
        ),
    ]
