# Generated by Django 4.1.7 on 2023-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_anketa_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anketa',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Birth_date',
        ),
        migrations.AddField(
            model_name='anketa',
            name='Place',
            field=models.CharField(max_length=100, null=True, verbose_name='Место оказания услуг'),
        ),
        migrations.AddField(
            model_name='anketa',
            name='Price',
            field=models.IntegerField(null=True, verbose_name='Стоимость оказания услуг'),
        ),
        migrations.AddField(
            model_name='anketa',
            name='Time',
            field=models.CharField(max_length=50, null=True, verbose_name='Сроки оказания услуг'),
        ),
        migrations.AddField(
            model_name='users',
            name='Notes',
            field=models.TextField(max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='users',
            name='Patronymic',
            field=models.CharField(default=1, max_length=50, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anketa',
            name='Text',
            field=models.TextField(max_length=1000, verbose_name='Текст анкеты'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='Tittle',
            field=models.CharField(max_length=100, verbose_name='Название анкеты'),
        ),
    ]
