# Generated by Django 4.1.7 on 2023-04-12 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор анкеты'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
