# Generated by Django 4.1.7 on 2023-04-13 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_anketa_author_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор анкеты'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='Price',
            field=models.CharField(max_length=100, null=True, verbose_name='Стоимость оказания услуг'),
        ),
    ]
