# Generated by Django 4.1.7 on 2023-04-13 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_anketa_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otkl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anketa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Анкета')),
                ('Otkl_User', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.anketa', verbose_name='Откликнувшийся пользователь')),
            ],
            options={
                'verbose_name': 'Откликания на анкеты',
                'verbose_name_plural': 'Откликания на анкеты',
                'ordering': ['Anketa', 'Otkl_User'],
            },
        ),
    ]
