# Generated by Django 4.1.7 on 2023-04-13 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_otkl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otkl',
            name='Anketa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.anketa', verbose_name='Анкета'),
        ),
        migrations.AlterField(
            model_name='otkl',
            name='Otkl_User',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Откликнувшийся пользователь'),
        ),
    ]
