# Generated by Django 4.1.7 on 2023-04-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_otkl_anketa_alter_otkl_otkl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='Lang_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lang_categori', verbose_name='Язык программирования'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='Soft_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.soft_categori', verbose_name='Категория софта'),
        ),
    ]
