# Generated by Django 4.2.5 on 2023-09-30 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_anketa_lang_cat_alter_anketa_soft_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anketa',
            name='Soft_cat',
        ),
    ]
