# Generated by Django 4.2.5 on 2023-09-30 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_lang_categori_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anketa',
            options={'ordering': ['Tittle'], 'verbose_name': 'Анкеты', 'verbose_name_plural': 'Анкеты'},
        ),
        migrations.AlterModelOptions(
            name='main_categori',
            options={'ordering': ['Tittle'], 'verbose_name': 'Основные категория', 'verbose_name_plural': 'Основные категория'},
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='Place',
        ),
        migrations.RemoveField(
            model_name='anketa',
            name='Time',
        ),
        migrations.AddField(
            model_name='anketa',
            name='Text2',
            field=models.TextField(default='Типа Текст', max_length=1000, verbose_name='Ключевые навыки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anketa',
            name='Lang_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lang_categori', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='Price',
            field=models.CharField(max_length=100, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='Text',
            field=models.TextField(max_length=1000, verbose_name='Описание анкеты'),
        ),
        migrations.AlterField(
            model_name='main_categori',
            name='Tittle',
            field=models.CharField(max_length=50, verbose_name='Основные категория'),
        ),
    ]
