# Generated by Django 4.2.1 on 2023-09-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_lang_categori_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_categori',
            options={'ordering': ['Tittle'], 'verbose_name': 'Основные категория', 'verbose_name_plural': 'Основные категория'},
        ),
        migrations.AlterField(
            model_name='lang_categori',
            name='Tittle',
            field=models.CharField(max_length=150, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='main_categori',
            name='Tittle',
            field=models.CharField(max_length=150, verbose_name='Основные категория'),
        ),
    ]
