# Generated by Django 4.2.5 on 2023-09-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_anketa_options_alter_main_categori_options_and_more'),
        ('main', '0018_alter_main_categori_options_and_more'),
    ]

    operations = [
    ]
