# Generated by Django 4.2.5 on 2023-09-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_merge_20230930_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anketa',
            options={'ordering': ['Tittle'], 'verbose_name': 'Анкеты пользователей', 'verbose_name_plural': 'Анкеты пользователей'},
        ),
        migrations.AlterField(
            model_name='anketa',
            name='Text',
            field=models.TextField(max_length=1000, verbose_name='Текст анкеты'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='Text2',
            field=models.TextField(max_length=1000, verbose_name='Проф пометки'),
        ),
        migrations.AlterField(
            model_name='main_categori',
            name='Tittle',
            field=models.CharField(max_length=150, verbose_name='Основные категория'),
        ),
        migrations.CreateModel(
            name='Otklik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=550, verbose_name='ФИО')),
                ('BirthDate', models.CharField(max_length=500, verbose_name='ФИО')),
                ('Email', models.EmailField(max_length=500, verbose_name='Почта')),
                ('Phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('Citizenship', models.CharField(max_length=300, verbose_name='Гражданство')),
                ('Place', models.CharField(max_length=300, verbose_name='Место жительства')),
                ('Portfolio', models.CharField(max_length=500, verbose_name='Ссылка на портфолио')),
                ('Rezume', models.CharField(max_length=500, verbose_name='Резюме')),
                ('DatePost', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('Anketa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.anketa', verbose_name='Вакансия на которую откликнулись')),
            ],
            options={
                'verbose_name': 'Отклики',
                'verbose_name_plural': 'Отклики',
                'ordering': ['DatePost'],
            },
        ),
    ]
