# Generated by Django 4.2.5 on 2023-09-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_otklik_birthdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Soft_categori',
        ),
    ]
