# Generated by Django 4.2.5 on 2023-09-30 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_delete_soft_categori'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anketa',
            options={'ordering': ['Tittle'], 'verbose_name': 'Вакансии', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='anketa',
            name='Author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор вакансии'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='Text',
            field=models.TextField(max_length=1000, verbose_name='Текст вакансии'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='Tittle',
            field=models.CharField(max_length=100, verbose_name='Название вакансии'),
        ),
        migrations.DeleteModel(
            name='Otkl',
        ),
    ]
